#!/bin/bash

# Load style
source "/etc/update-motd.d/default"
source "$DEFAULT_THEME"

# Fetch Information
device_model="$(tr -d '\0' < /sys/firmware/devicetree/base/model)"
kernel_release="$(uname -sr)"

# Hour formatted date
if [[ "$24_HOUR_FORMAT" == "true" ]]; then
    login_date="$(date +"%a %b %d %Y, %H:%M %:z")"
else
    login_date="$(date +"%a %b %d %Y, %I:%M %p %:z")"
fi

# OUTPUT
echo -e "\n $(color $inv_title " $device_model ")$(color $inv_muted " $kernel_release ")"
echo -e "\n $bullet Welcome $(color $inv_accent " $(logname) ") to $(color $accent @$(hostname)) $(color $muted "at $login_date")\n"
