#!/bin/bash

# Load style
source "/etc/update-motd.d/default"
source "$DEFAULT_THEME"

# Fetch Information
device_model="$(tr -d '\0' < /sys/firmware/devicetree/base/model)"
kernel_release="$(uname -sr)"
login_date="$(date +"%a %b %d %Y, %I:%M %p %:z")"

# OUTPUT
echo -e "\n $(color $inv_title " $device_model ")$(color $inv_muted " $kernel_release ")"
echo -e "\n $bullet Welcome $(color $inv_accent " $(logname) ") to $(color $accent @$(hostname)) $(color $muted "at $login_date")\n"
