#!/bin/bash

# Load style
source "/etc/update-motd.d/default"
source "$DEFAULT_THEME"

# Fetch Information
update_count="$(apt-get --just-print upgrade | grep -c "^Inst")"

# Default colors
update_color="$muted"
update_inv_color="$inv_muted"

s="s"

# Adjust colors and pluralization and colors if there are upgradable packages
if [ "$update_count" -gt 0 ]; then

    update_color="$accent"
    update_inv_color="$inv_accent"

    if [ "$update_count" -eq 1 ]; then
        s=""
    fi
fi

# OUTPUT
echo -e "\n $(color $update_color "$bullet") $(color $update_inv_color " $update_count ") $(color $update_color "package$s can be upgraded")\n"
