#!/bin/bash

# Load style
source "/etc/update-motd.d/default"
source "$DEFAULT_THEME"

# Fetch Information
if [[ "$REFRESH_UPDATE_COUNT" == "true" ]]; then
    apt update -qqq
fi
upgrade_count=$(apt list --upgradable 2>/dev/null | grep -c 'upgradable')

# Defaults
upgrade_color="$muted"
upgrade_inv_color="$inv_muted"
s="s"

# Check if there are updates
if [ "$upgrade_count" -gt 0 ]; then

    upgrade_color="$accent"
    upgrade_inv_color="$inv_accent"

    if [ "$upgrade_count" -eq 1 ]; then
        s=""
    fi
fi

# OUTPUT
echo -e "\n $(color $upgrade_color "$bullet") $(color $upgrade_inv_color " $upgrade_count ") $(color $upgrade_color "package$s can be upgraded")\n"
